language: node_js
node_js:
  - "6"
  - "7"
sudo: false
script: "gulp coverage"
notifications:
  email: false
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
